import UixyTable from "./Table.component.vue";
import {
  type UixyTableProps,
  type UixyTableEmits,
  type UixyTableSlots,
  type UixyTableColumn,
  type UixyTableColumnKey,
  type UixyTableSort,
  type UixyTableSortDirection,
  type UixyTablePagination,
  type UixyTableFilter,
  type UixyTableRowKey,
  type UixyTableAlign,
  type UixyTableDensity,
  type UixyTableCellSlotProps,
  type UixyTableSummarySlotProps,
  type UixyTableFilterSlotProps,
  type UixyTablePaginationSlotProps,
} from "./Table.types";

export {
  UixyTable,
  type UixyTableProps,
  type UixyTableEmits,
  type UixyTableSlots,
  type UixyTableColumn,
  type UixyTableColumnKey,
  type UixyTableSort,
  type UixyTableSortDirection,
  type UixyTablePagination,
  type UixyTableFilter,
  type UixyTableRowKey,
  type UixyTableAlign,
  type UixyTableDensity,
  type UixyTableCellSlotProps,
  type UixyTableSummarySlotProps,
  type UixyTableFilterSlotProps,
  type UixyTablePaginationSlotProps,
};
